// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Categories",
    columns: [
      { name: "name", type: "string" },
      { name: "xataupdatedAt", type: "datetime" },
      { name: "xataversion", type: "int" },
      { name: "xatacreatedAt", type: "string" },
    ],
  },
  {
    name: "Contact",
    columns: [
      { name: "xatacreatedAt", type: "string" },
      { name: "xataupdatedAt", type: "string" },
      { name: "xataversion", type: "int" },
      { name: "fullName", type: "string" },
      { name: "num", type: "string" },
      { name: "email", type: "email" },
      { name: "message", type: "string" },
    ],
  },
  {
    name: "Demande_P",
    columns: [
      { name: "xatacreatedAt", type: "string" },
      { name: "xataupdatedAt", type: "string" },
      { name: "xataversion", type: "int" },
      { name: "nameP", type: "string" },
      { name: "idP", type: "string" },
      { name: "fullName", type: "string" },
      { name: "num", type: "string" },
      { name: "mail", type: "email" },
    ],
  },
  {
    name: "Products",
    columns: [
      { name: "product", type: "text" },
      { name: "price", type: "int" },
      { name: "img", type: "multiple" },
      { name: "categorie", type: "string" },
      { name: "niche", type: "string" },
      { name: "discount", type: "int" },
      { name: "description", type: "text" },
      { name: "xatacreatedAt", type: "string" },
      { name: "xataupdatedAt", type: "string" },
      { name: "xataversion", type: "int" },
    ],
  },
  {
    name: "Reviews",
    columns: [
      { name: "product", type: "string" },
      { name: "img", type: "string" },
      { name: "xatacreatedAt", type: "string" },
      { name: "xataupdatedAt", type: "string" },
      { name: "xataversion", type: "int" },
      { name: "user", type: "string" },
      { name: "comment", type: "text" },
      { name: "rate", type: "int" },
    ],
  },
  {
    name: "Subcategories",
    columns: [
      { name: "niche", type: "string" },
      { name: "xatacreatedAt", type: "string" },
      { name: "xataupdatedAt", type: "string" },
      { name: "xataversion", type: "int" },
      { name: "name", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Categories = InferredTypes["Categories"];
export type CategoriesRecord = Categories & XataRecord;

export type Contact = InferredTypes["Contact"];
export type ContactRecord = Contact & XataRecord;

export type DemandeP = InferredTypes["Demande_P"];
export type DemandePRecord = DemandeP & XataRecord;

export type Products = InferredTypes["Products"];
export type ProductsRecord = Products & XataRecord;

export type Reviews = InferredTypes["Reviews"];
export type ReviewsRecord = Reviews & XataRecord;

export type Subcategories = InferredTypes["Subcategories"];
export type SubcategoriesRecord = Subcategories & XataRecord;

export type DatabaseSchema = {
  Categories: CategoriesRecord;
  Contact: ContactRecord;
  Demande_P: DemandePRecord;
  Products: ProductsRecord;
  Reviews: ReviewsRecord;
  Subcategories: SubcategoriesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://labase-kz-s-workspace-6ue324.eu-central-1.xata.sh/db/KzLocation",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
