/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wwHDzkar3US
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.375rem;
}
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function ContactAiGen() {
  return (
    <div className="bg-white dark:bg-gray-950 text-gray-900 dark:text-gray-50 min-h-[100dvh] flex flex-col">
      <main className="flex-1 py-12 md:py-24 lg:py-32">
        <div className="container max-w-7xl mx-auto px-4 md:px-6">
          <div className="grid md:grid-cols-2 gap-12 animate-fadeInUp">
            <div className="space-y-6">
              <h1 className="text-4xl font-bold animate-fadeIn">Contact Us</h1>
              <p className="text-gray-500 dark:text-gray-400 animate-fadeIn">
                Get in touch with us for more information about our services.
              </p>
              <div className="space-y-4 animate-fadeIn">
                <div className="flex items-start gap-4">
                  <div className="h-6 w-6 text-gray-500 dark:text-gray-400 mt-1 animate-bounce">
                    <PhoneIcon  />
                  </div>
                  <div>
                    <h3 className="font-medium animate-fadeIn">Phone</h3>
                    <p className="text-gray-500 dark:text-gray-400 animate-fadeIn">+1 (555) 555-5555</p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="h-6 w-6 text-gray-500 dark:text-gray-400 mt-1 animate-bounce">
                    <MapPinIcon />
                  </div>
                  <div>
                    <h3 className="font-medium animate-fadeIn">Location</h3>
                    <p className="text-gray-500 dark:text-gray-400 animate-fadeIn">123 Main St, Anytown USA</p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="h-6 w-6 text-gray-500 dark:text-gray-400 mt-1 animate-bounce">
                    <MailIcon/>
                  </div>
                  <div>
                    <h3 className="font-medium animate-fadeIn">Email</h3>
                    <p className="text-gray-500 dark:text-gray-400 animate-fadeIn">info@acmeinc.com</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 md:p-8 animate-fadeInUp">
              <h2 className="text-2xl font-bold mb-4 animate-fadeIn">Get in Touch</h2>
              <form className="space-y-4 animate-fadeIn">
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <Input className="animate-pulse" id="name" placeholder="Enter your name" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input className="animate-pulse" id="email" placeholder="Enter your email" type="email" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="message">Message</Label>
                  <Textarea className="min-h-[120px] animate-pulse" id="message" placeholder="Enter your message" />
                </div>
                <Button className="w-full animate-bounce" type="submit">
                  Send Message
                </Button>
              </form>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function MailIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MapPinIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}


function PhoneIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}
